# Generated by Django 4.2.7 on 2023-11-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='emoji',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
