# Generated by Django 4.2.7 on 2023-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(choices=[('🤣 смешное', '🤣 смешное'), ('😊 няшное', '😊 няшное'), ('😭 грустное', '😭 грустное'), ('🍓 секси', '🍓 секси'), ('😱 страшное', '😱 страшное'), ('😟 кринж', '😟 кринж'), ('🧐 ностальгическое', '🧐 ностальгическое'), ('😈 злобное', '😈 злобное')], max_length=50),
        ),
    ]
