# Generated by Django 4.2.7 on 2023-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emotion_emoji_alter_emotion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='codename',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
