# Generated by Django 4.2.7 on 2023-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emotion_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.CharField(blank=True, db_column='url', max_length=255),
        ),
        migrations.RenameField(
            model_name='content',
            old_name='url',
            new_name='youtube_id',
        ),
    ]
