# Generated by Django 4.2.7 on 2023-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_content_url_rename_url_content_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
