# Generated by Django 4.2.7 on 2023-11-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_content_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='ContentEmotionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('emotion_count_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emotioncount')),
            ],
        ),
    ]
