# Generated by Django 4.2.7 on 2023-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_content_emotion_angry_content_emotion_awkward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
